export interface MonacoThemeData {
  base: "vs" | "vs-dark" | "hc-black" | "hc-light";
  inherit: boolean;
  rules: { token: string; foreground?: string; background?: string; fontStyle?: string }[];
  colors: Record<string, string>;
}

export const tableOpenDarkTheme: MonacoThemeData = {
  base: "vs-dark",
  inherit: false,
  rules: [
    { token: "", foreground: "EBECED", background: "0A0B0D" },
    { token: "keyword", foreground: "C792EA", fontStyle: "normal" },
    { token: "keyword.sql", foreground: "C792EA", fontStyle: "normal" },
    { token: "type", foreground: "D4A84A" },
    { token: "type.identifier", foreground: "D4A84A" },
    { token: "string", foreground: "C3E88D" },
    { token: "string.sql", foreground: "C3E88D" },
    { token: "number", foreground: "F78C6C" },
    { token: "number.sql", foreground: "F78C6C" },
    { token: "delimiter", foreground: "89DDFF" },
    { token: "comment", foreground: "656B73", fontStyle: "italic" },
    { token: "comment.sql", foreground: "656B73", fontStyle: "italic" },
    { token: "comment.block", foreground: "656B73", fontStyle: "italic" },
    { token: "function", foreground: "82AAFF" },
    { token: "variable", foreground: "EBECED" },
    { token: "parameter", foreground: "C9CCD1" },
  ],
  colors: {
    "editor.background": "#0a0b0d",
    "editor.foreground": "#ebeced",
    "editor.lineHighlightBackground": "rgba(255,255,255,0.035)",
    "editor.selectionBackground": "rgba(255,255,255,0.09)",
    "editor.inactiveSelectionBackground": "rgba(255,255,255,0.04)",
    "editorCursor.foreground": "#ebeced",
    "editorLineNumber.foreground": "#656b73",
    "editorLineNumber.activeForeground": "#9da3aa",
    "editor.selectionHighlightBackground": "rgba(212,145,42,0.12)",
    "editor.findMatchHighlightBackground": "rgba(212,145,42,0.28)",
    "editorBracketMatch.background": "rgba(235,236,237,0.15)",
    "editorBracketMatch.border": "rgba(235,236,237,0.45)",
    "editorGutter.background": "#0a0b0d",
    "editorWidget.background": "#1a1d22",
    "editorWidget.border": "rgba(255,255,255,0.08)",
    "input.background": "#121417",
    "input.foreground": "#ebeced",
    "input.border": "rgba(255,255,255,0.08)",
    "list.activeSelectionBackground": "#23272d",
    "list.hoverBackground": "#1a1d22",
    "editorSuggestWidget.background": "#1a1d22",
    "editorSuggestWidget.border": "rgba(255,255,255,0.08)",
  },
};

export const tableOpenLightTheme: MonacoThemeData = {
  base: "vs",
  inherit: false,
  rules: [
    { token: "", foreground: "1A1C1E", background: "FAFAFB" },
    { token: "keyword", foreground: "7C3AED", fontStyle: "normal" },
    { token: "keyword.sql", foreground: "7C3AED", fontStyle: "normal" },
    { token: "type", foreground: "B87A1E" },
    { token: "type.identifier", foreground: "B87A1E" },
    { token: "string", foreground: "237A48" },
    { token: "string.sql", foreground: "237A48" },
    { token: "number", foreground: "C24130" },
    { token: "number.sql", foreground: "C24130" },
    { token: "delimiter", foreground: "0891B2" },
    { token: "comment", foreground: "848993", fontStyle: "italic" },
    { token: "comment.sql", foreground: "848993", fontStyle: "italic" },
    { token: "comment.block", foreground: "848993", fontStyle: "italic" },
    { token: "function", foreground: "2563EB" },
    { token: "variable", foreground: "1A1C1E" },
    { token: "parameter", foreground: "3D4147" },
  ],
  colors: {
    "editor.background": "#fafafb",
    "editor.foreground": "#1a1c1e",
    "editor.lineHighlightBackground": "rgba(0,0,0,0.035)",
    "editor.selectionBackground": "rgba(0,0,0,0.08)",
    "editor.inactiveSelectionBackground": "rgba(0,0,0,0.03)",
    "editorCursor.foreground": "#1a1c1e",
    "editorLineNumber.foreground": "#848993",
    "editorLineNumber.activeForeground": "#595e66",
    "editor.selectionHighlightBackground": "rgba(184,122,30,0.12)",
    "editor.findMatchHighlightBackground": "rgba(184,122,30,0.25)",
    "editorBracketMatch.background": "rgba(26,28,30,0.09)",
    "editorBracketMatch.border": "rgba(26,28,30,0.45)",
    "editorGutter.background": "#fafafb",
    "editorWidget.background": "#f3f4f6",
    "editorWidget.border": "rgba(0,0,0,0.08)",
    "input.background": "#ffffff",
    "input.foreground": "#1a1c1e",
    "input.border": "rgba(0,0,0,0.08)",
    "list.activeSelectionBackground": "#e2e4e8",
    "list.hoverBackground": "#ebecef",
    "editorSuggestWidget.background": "#f3f4f6",
    "editorSuggestWidget.border": "rgba(0,0,0,0.08)",
  },
};
